version: "3"
services:
    ddclient:
        restart: unless-stopped
        image: linuxserver/ddclient
        container_name: ddclient
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Bangkok
        volumes:
            - ./ddclient/config:/config

    rpi-busybox-httpd:
        restart: unless-stopped
        image: hypriot/rpi-busybox-httpd
        container_name: rpi-busybox-httpd
        ports:
            - 3000:80

volumes:
    letsencrypt:
